/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package q2;

import javax.swing.JOptionPane;

/**
 *
 * @author Tuan Anh
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitLogin = new javax.swing.JMenuItem();
        mitExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Ha Noi ngay nang nong! Toi met moi den \nlop. Toi co gang tap trung hoc bai vi toi\nbiet sap thi PE roi. Nhung hom nay toi \nthay hoc kha vao, co the do toi lam duoc\nbai.");
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("File");

        mitLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mitLogin.setText("Login");
        mitLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitLoginActionPerformed(evt);
            }
        });
        jMenu1.add(mitLogin);

        mitExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        mitExit.setText("Exit");
        mitExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitExitActionPerformed(evt);
            }
        });
        jMenu1.add(mitExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitLoginActionPerformed
        // TODO add your handling code here:
        NewJDialog dial = new NewJDialog(this, true);
        dial.setVisible(true);
    }//GEN-LAST:event_mitLoginActionPerformed

    private void mitExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitExitActionPerformed
        // TODO add your handling code here:
        int click =  JOptionPane.showConfirmDialog(this, "Do you really wanna exit application ?", "Question", JOptionPane.YES_NO_OPTION);
        if(click == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mitExitActionPerformed
    public int count(){
        int count = 0;
        String s = jTextArea1.getText().toLowerCase();
        String [] ss = s.split("\\s+");
        for(String x : ss){
            if(x.equalsIgnoreCase("toi")){
                count++;
            }
        }
        return count;
    }
    public void process(String teacher, String email, boolean showEmail){
        int count = count();
        if(showEmail){
            if(count > 4){
                jTextArea1.setText("Teacher : "+teacher+"\nthe document too more \"toi\" words \ncontact : "+email);
            }else if (count < 2){
                jTextArea1.setText("Teacher : "+teacher+"\nthe document a little \"toi\" words \ncontact : "+email);
            }else{
                jTextArea1.setText("Teacher : "+teacher+"\nthe document ok \ncontact : "+email);
            }
        }else{
            if(count > 4){
                jTextArea1.setText("Teacher : "+teacher+"\nthe document too more \"toi\" words \n");
            }else if (count < 2){
                jTextArea1.setText("Teacher : "+teacher+"\nthe document a little \"toi\" words \n");
            }else{
                jTextArea1.setText("Teacher : "+teacher+"\nthe document ok \n");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenuItem mitExit;
    private javax.swing.JMenuItem mitLogin;
    // End of variables declaration//GEN-END:variables
}
